<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Booking Report - {{ date('d-m-Y') }}</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; font-size: 11px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #DB6574; padding-bottom: 10px; }
        .header h1 { color: #DB6574; margin: 0; text-transform: uppercase; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background-color: #DB6574; color: white; padding: 10px 5px; text-transform: uppercase; font-size: 10px; }
        td { border-bottom: 1px solid #ddd; padding: 8px 5px; text-align: center; }
        
        .customer-info { text-align: left; }
        .price { font-weight: bold; color: #28a745; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: right; font-size: 9px; color: #777; border-top: 1px solid #ddd; padding-top: 5px; }
        
        /* សម្រាប់បង្ហាញ Status ជាពណ៌ */
        .status-waiting { color: #ffc107; font-weight: bold; }
        .status-approved { color: #28a745; font-weight: bold; }
        .status-rejected { color: #dc3545; font-weight: bold; }
    </style>
</head>
<body>

    <div class="header">
        <h1>Hotel Management System</h1>
        <p>Report: All Booking Reservations</p>
        <p>Date Generated: {{ date('d M Y, h:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Customer Details</th>
                <th>Room Title</th>
                <th>Check In/Out</th>
                <th>Nights</th>
                <th>Price/Night</th>
                <th>Total Payment</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($bookings as $booking)
                @php
                    $startDate = \Carbon\Carbon::parse($booking->start_date);
                    $endDate = \Carbon\Carbon::parse($booking->end_date);
                    $totalNights = $startDate->diffInDays($endDate) ?: 1; 
                    $pricePerNight = $booking->room->price ?? 0;
                    $totalPayment = $totalNights * $pricePerNight;
                @endphp
                <tr>
                    <td style="font-weight: bold;">#{{ $booking->id }}</td>
                    <td class="customer-info">
                        <b>{{ $booking->name }}</b><br>
                        {{ $booking->phone }}<br>
                        <small>{{ $booking->email }}</small>
                    </td>
                    <td>{{ $booking->room->room_title ?? 'N/A' }}</td>
                    <td>
                        {{ $booking->start_date }}<br>
                        <span style="color: #666;">to</span><br>
                        {{ $booking->end_date }}
                    </td>
                    <td>{{ $totalNights }} Nights</td>
                    <td>${{ number_format($pricePerNight, 2) }}</td>
                    <td class="price">${{ number_format($totalPayment, 2) }}</td>
                    <td>
                        <span class="status-{{ $booking->status }}">
                            {{ ucfirst($booking->status) }}
                        </span>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by System Admin - Page 1 of 1
    </div>

</body>
</html>