<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Booking Report - {{ date('d-m-Y') }}</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; font-size: 11px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #DB6574; padding-bottom: 10px; }
        .header h1 { color: #DB6574; margin: 0; text-transform: uppercase; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background-color: #DB6574; color: #fff; padding: 10px 5px; text-transform: uppercase; font-size: 10px; }
        td { border-bottom: 1px solid #ddd; padding: 8px 5px; text-align: center; }
        .customer { text-align: left; }
        .price { font-weight: bold; color: #28a745; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: right; font-size: 9px; color: #777; border-top: 1px solid #ddd; padding-top: 5px; }
        .status-waiting  { color: #ffc107; font-weight: bold; }
        .status-approved { color: #28a745; font-weight: bold; }
        .status-rejected { color: #dc3545; font-weight: bold; }
    </style>
</head>
<body>

    <div class="header">
        <h1>{{ config('app.name') }}</h1>
        <p>Report: All Booking Reservations</p>
        <p>Generated: {{ date('d M Y, h:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th><th>Customer</th><th>Room</th><th>Check In / Out</th>
                <th>Nights</th><th>Price / Night</th><th>Total</th><th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($bookings as $booking)
                @php
                    $nights = max(1, (int) \Carbon\Carbon::parse($booking->start_date)->diffInDays(\Carbon\Carbon::parse($booking->end_date)));
                    $price  = $booking->room->price ?? 0;
                @endphp
                <tr>
                    <td><b>#{{ $booking->id }}</b></td>
                    <td class="customer">
                        <b>{{ $booking->name }}</b><br>
                        {{ $booking->phone }}<br>
                        <small>{{ $booking->email }}</small>
                    </td>
                    <td>{{ $booking->room->room_title ?? 'N/A' }}</td>
                    <td>{{ $booking->start_date }}<br><span style="color:#666;">to</span><br>{{ $booking->end_date }}</td>
                    <td>{{ $nights }}</td>
                    <td>${{ number_format($price, 2) }}</td>
                    <td class="price">${{ number_format($nights * $price, 2) }}</td>
                    <td><span class="status-{{ $booking->status }}">{{ ucfirst($booking->status) }}</span></td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">Generated by {{ config('app.name') }} admin</div>

</body>
</html>